using Microsoft.EntityFrameworkCore;
using Serilog;
using BooksApi.Data;
using BooksApi.Middleware;
using BooksApi.Repositories;
using BooksApi.Services;

// ─────────────────────────────────────────────────────────────────────────────
// PROGRAM.CS — The Application Entry Point
//
// In .NET 6+, Program.cs uses the "minimal hosting model" — no Startup.cs needed.
// It has two phases:
//   1. BUILD PHASE   → Register services in the DI container
//   2. RUNTIME PHASE → Configure the HTTP request pipeline (middleware)
// ─────────────────────────────────────────────────────────────────────────────

// ── Configure Serilog (structured logging) ───────────────────────────────────
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Information()
    .WriteTo.Console(outputTemplate:
        "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
    .WriteTo.File("logs/booksapi.log",
        rollingInterval: RollingInterval.Day,
        outputTemplate: "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
    .CreateLogger();

var builder = WebApplication.CreateBuilder(args);

// Replace default .NET logging with Serilog
builder.Host.UseSerilog();

// ════════════════════════════════════════════════════════════════════════════
// BUILD PHASE — Register Services in the DI Container
// ════════════════════════════════════════════════════════════════════════════

// ── Controllers ──────────────────────────────────────────────────────────────
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        // Return camelCase JSON (standard for APIs)
        options.JsonSerializerOptions.PropertyNamingPolicy =
            System.Text.Json.JsonNamingPolicy.CamelCase;
    });

// ── Swagger / OpenAPI Documentation ──────────────────────────────────────────
// Swagger automatically generates interactive API documentation from your code
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "Books API",
        Version = "v1",
        Description = "A RESTful microservice for managing books — built with ASP.NET Core",
        Contact = new Microsoft.OpenApi.Models.OpenApiContact
        {
            Name = "Iniyan",
            Email = "iniyanstarzz@gmail.com"
        }
    });

    // Include XML comments from your code in Swagger docs
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
        options.IncludeXmlComments(xmlPath);
});

// ── Database (Entity Framework Core) ─────────────────────────────────────────
// Using SQLite for development — easy to swap to SQL Server/PostgreSQL in prod
builder.Services.AddDbContext<AppDbContext>(options =>
{
    var env = builder.Environment;

    if (env.IsEnvironment("Testing"))
    {
        // In-memory DB for unit tests — no file, no setup needed
        options.UseInMemoryDatabase("BooksApiTest");
    }
    else
    {
        // SQLite — creates a .db file in the project root
        options.UseSqlite(
            builder.Configuration.GetConnectionString("DefaultConnection")
            ?? "Data Source=books.db");
    }

    // In development, log all SQL queries generated by EF Core
    if (env.IsDevelopment())
        options.EnableSensitiveDataLogging().LogTo(Console.WriteLine);
});

// ── Dependency Injection — Registering Our Services ──────────────────────────
//
// LIFETIME OPTIONS:
//   Scoped    → New instance per HTTP request (most common for services/repos)
//   Singleton → One instance for the entire application lifetime
//   Transient → New instance every time it's requested
//
// Services that use DbContext must be Scoped (DbContext is Scoped by default).

builder.Services.AddScoped<IBookRepository, BookRepository>();
builder.Services.AddScoped<IBookService, BookService>();

// ── CORS (Cross-Origin Resource Sharing) ─────────────────────────────────────
// Allows browsers from other domains to call this API (e.g., a React frontend)
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader());
});

var app = builder.Build();

// ════════════════════════════════════════════════════════════════════════════
// RUNTIME PHASE — Configure the HTTP Request Pipeline
// Order matters! Middleware runs in the order it's registered.
// ════════════════════════════════════════════════════════════════════════════

// 1. Global exception handling — must be FIRST so it catches all errors
app.UseGlobalExceptionMiddleware();

// 2. Request/response logging
app.UseRequestLogging();

// 3. Swagger — only in development (don't expose docs in production)
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "Books API v1");
        options.RoutePrefix = string.Empty; // Serve Swagger at root "/"
    });
}

// 4. CORS
app.UseCors("AllowAll");

// 5. HTTPS redirection
app.UseHttpsRedirection();

// 6. Authorization middleware (even without auth configured, this is standard)
app.UseAuthorization();

// 7. Route to controllers
app.MapControllers();

// ── Database Initialization ───────────────────────────────────────────────────
// Apply migrations and seed data on startup
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    try
    {
        // EnsureCreated creates the DB if it doesn't exist (for SQLite/InMemory)
        // In production with migrations, use: db.Database.Migrate()
        db.Database.EnsureCreated();
        logger.LogInformation("Database initialized successfully");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Failed to initialize database");
        throw;
    }
}

Log.Information("Books API starting up on {Environment}", app.Environment.EnvironmentName);
app.Run();

// Make Program class accessible for integration tests
public partial class Program { }